#!/bin/bash

excludeList="lib/**/*.freezed.dart lib/core/*"

flutter test --coverage
echo $excludeList | xargs lcov --remove coverage/lcov.info -o coverage/lcov.info
genhtml coverage/lcov.info -o coverage/
