name: pings
description: Collaborative alarm app.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.1
  numberpicker: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  very_good_analysis: ^2.0.3
  build_runner: ^2.0.2
  google_fonts: ^2.0.0
  mockito: ^5.0.7

flutter:
  uses-material-design: true
  fonts:
   - family: pings
     fonts:
      - asset: assets/fonts/pings.ttf
