on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Test and Coveralls
jobs:
  build:
    name: Run tests and upload to coveralls
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: code

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Cache Flutter
      id: flutter-cache
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ env.cache-name }}-ubuntu-latest-pings-${{ hashFiles('code/pings/pubspec.lock') }}
        restore-keys: |
          ${{ env.cache-name }}-ubuntu-latest-pings-
          ${{ env.cache-name }}-ubuntu-latest-
          ${{ env.cache-name }}-
      env:
        cache-name: flutter-cache

    - name: Setup Flutter
      if: steps.flutter-cache.outputs.cache-hit != 'true'
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.x'
        channel: 'stable'

    - name: Get packages
      working-directory: code/pings
      run: flutter pub get

    - name: Generate required files
      working-directory: code/pings
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Analyze Project
      working-directory: code/pings
      run: flutter analyze
      continue-on-error: true

    - name: Run tests and generate lcov.info
      working-directory: code/pings
      run: flutter test --coverage

    - name: Remove files from lcov.info
      working-directory: code/pings
      run: |
        flutter pub global activate remove_from_coverage
        flutter pub global run remove_from_coverage -f coverage/lcov.info -r '\.freezed\.dart'

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: code/pings/coverage/lcov.info
        base-path: code/pings
