on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Test and Coveralls

jobs:
  build:
    name: Run tests and upload to coveralls
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subsito/flutter-action@v1
      with:
        flutter-version: '2.0.x'

    - name: Get packages
      working-directory: ./pings
      run: flutter pub get

    - name: Analyze Project
      working-directory: ./pings
      run: flutter analyze
      continue-on-error: true

    - name: Generate required files
      working-directory: ./pings
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run tests and generate lcov.info
      working-directory: ./pings
      run: flutter test --coverage

    - name: Very good coverage - exclude generated files from coverage info
      uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      with:
        path: ./pings/coverage/lcov.info
        min_coverage: 80
        exclude: "**/*.freezed.dart"

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: ./pings

